/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif

/* These two lines were needed to get this to compile sept 2014*/
#include <string.h>
static int check_tz();

#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE EP_restart( EP_in )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int EP_leng;
extern FILE *EP_in, *EP_out;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up EP_text. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up EP_text again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via EP_restart()), so that the user can continue scanning by
	 * just pointing EP_in at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when EP_text is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int EP_leng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow EP_wrap()'s to do buffer switches
 * instead of setting up a fresh EP_in.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void EP_restart YY_PROTO(( FILE *input_file ));

void EP_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void EP_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE EP_create_buffer YY_PROTO(( FILE *file, int size ));
void EP_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void EP_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void EP_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER EP_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE EP_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE EP_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE EP_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer EP_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = EP_create_buffer( EP_in, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = EP_create_buffer( EP_in, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *EP_in = (FILE *) 0, *EP_out = (FILE *) 0;
typedef int yy_state_type;
extern char *EP_text;
#define yytext_ptr EP_text

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up EP_text.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	EP_leng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 50
#define YY_END_OF_BUFFER 51
static yyconst short int yy_accept[291] =
    {   0,
        0,    0,   51,   49,   47,   46,   45,   49,   49,   23,
       23,   23,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,    0,   22,   18,    1,    0,   23,    0,
       23,   23,   41,   48,   43,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   44,   48,   21,    1,    0,   23,
       42,    0,    0,    0,    0,    0,    0,    0,    0,   23,
       23,    0,    8,   12,   16,    6,    5,   11,   10,    7,
        9,   15,   17,   14,   13,    0,   23,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   20,   20,
        0,   24,   48,   48,   48,   48,   48,   11,   10,   48,

       48,   48,   48,    2,    0,   23,    0,   25,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       23,   24,    8,   48,   48,   48,   48,    7,   48,   48,
       48,    0,   25,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   23,   12,   48,   48,
       48,   48,   48,   48,    0,    0,   26,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   19,
       48,   48,    5,   48,   14,   48,    0,    4,   26,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   16,    6,   15,   48,    0,    0,   27,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   13,    3,   27,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   28,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   32,   32,   36,   36,   40,   40,   30,   30,
       29,   29,   35,   35,   34,   34,   31,   31,   33,   33,
       39,   39,   38,   38,   37,   37,   32,   36,   40,   30,
       29,    0,   35,   34,   31,   33,   39,   38,   37,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    1,    1,    1,    1,    1,    1,    5,
        6,    1,    1,    7,    8,    9,   10,   11,   12,   13,
       14,   14,   14,   14,   14,   14,   15,   16,    1,    1,
        1,    1,    1,    1,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       27,   33,   34,   35,   36,   37,   38,   27,   39,   27,
        1,    1,    1,    1,    1,    1,   17,   18,   19,   20,

       21,   22,   23,   24,   25,   26,   27,   28,   29,   30,
       31,   32,   27,   33,   34,   35,   36,   37,   38,   27,
       39,   27,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[40] =
    {   0,
        1,    1,    1,    1,    1,    2,    1,    3,    4,    5,
        6,    6,    6,    6,    6,    7,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8
    } ;

static yyconst short int yy_base[351] =
    {   0,
        0,    0,  860,  861,  861,  861,  861,   29,   34,   43,
      844,  847,   49,   36,    0,  836,  835,   34,  838,  823,
      834,  823,  830,  844,  840,  861,   62,   67,   76,   82,
      110,  120,  832,    0,    0,  814,  823,  826,  826,  813,
       39,   67,   72,  807,    0,  809,  861,  126,  830,  135,
      823,   69,  817,  816,   67,  819,  804,  815,  812,  145,
      155,  823,  806,  794,  808,  795,  791,  787,  804,  805,
        0,  802,    0,  791,  786,  161,  170,  811,  786,  795,
      798,  798,  785,  159,  155,  777,  778,  780,  184,    0,
      189,  802,  782,  775,  779,  771,  789,    0,    0,  781,

      775,  785,  781,  194,  199,  793,  204,   98,  784,  783,
      782,  781,  780,  779,  778,  777,  776,  775,  774,  773,
      213,  219,    0,  753,  769,  769,  752,    0,  766,  762,
      753,  224,  229,  772,  234,  239,  244,  249,  254,  259,
      264,  269,  274,  279,  284,  289,  298,    0,  759,  746,
      739,  756,  743,  757,  766,  304,  311,  757,  756,  755,
      754,  753,  752,  751,  750,  749,  748,  747,  746,  753,
      727,  720,    0,  725,    0,  736,  310,  861,  317,  747,
      322,  327,  332,  337,  342,  347,  352,  357,  362,  367,
      372,  377,    0,    0,    0,  722,  382,  387,  394,  738,

      737,  736,  735,  734,  733,  732,  730,  727,  724,  721,
      718,    0,  861,  393,  400,  405,  410,  415,  420,  425,
      430,  435,  440,  445,  450,  455,  460,  465,  715,  712,
      709,  706,  703,  700,  697,  694,  643,  616,  615,  612,
      616,  613,  604,  601,  600,  599,  596,  593,  400,  317,
      297,  212,  470,  184,  475,  183,  480,  182,  485,  181,
      490,  154,  495,  144,  500,  134,  505,  119,  510,  109,
      515,  106,  520,   89,  525,   62,  530,  535,  540,  545,
      550,   57,  555,  560,  565,  570,  575,  580,  585,  861,
      598,  605,  608,  609,  612,  613,  617,  620,  623,  627,

      628,  630,  632,  634,  636,  638,  640,  642,  644,  646,
      648,  650,  654,  655,  657,  659,  661,  663,  665,  667,
      669,  671,  673,  675,  677,  679,  681,  683,  685,  687,
      689,  691,  693,  695,  697,  699,  701,  705,  708,  711,
      714,  717,  720,  723,  726,  729,  732,  735,  738,  741
    } ;

static yyconst short int yy_def[351] =
    {   0,
      290,    1,  290,  290,  290,  290,  290,  290,  290,  290,
       10,   10,  290,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  292,  293,  290,  290,  290,  290,  290,
      290,  290,  294,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  290,  290,  295,  290,
      296,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  297,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  290,  290,  298,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,   77,   77,
      290,  297,  291,  291,  291,  291,  291,  291,  291,  291,

      291,  291,  291,  290,  290,   77,  290,  298,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  290,  290,  299,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  291,  291,  291,
      291,  291,  291,  291,  300,  290,  299,  301,  302,  303,
      304,  305,  306,  307,  308,  309,  310,  311,  312,   77,
      291,  291,  291,  291,  291,  291,  290,  290,  290,  313,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  291,  291,  291,  291,  290,  290,  313,  314,

      315,  316,  317,  318,  319,  320,  321,  322,  323,  324,
      325,  291,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  326,  327,
      328,  329,  330,  331,  332,  333,  334,  335,  336,  337,
      338,  339,  340,  341,  342,  343,  344,  345,  346,  347,
      348,  349,  290,  338,  290,  339,  290,  340,  290,  341,
      290,  350,  290,  343,  290,  344,  290,  345,  290,  346,
      290,  347,  290,  348,  290,  349,  290,  290,  290,  290,
      290,  350,  290,  290,  290,  290,  290,  290,  290,    0,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,

      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290
    } ;

static yyconst short int yy_nxt[901] =
    {   0,
        4,    5,    6,    7,    8,    4,    4,    9,    4,    4,
       10,   11,   12,   10,   10,   13,   14,   15,   15,   16,
       15,   17,   15,   15,   15,   18,   15,   15,   19,   20,
       21,   22,   15,   23,   15,   15,   15,   15,   15,   24,
       24,   24,   24,   24,   25,   25,   25,   25,   25,   26,
       40,   27,   28,   29,   29,   29,   29,   29,   30,   33,
       33,   33,   33,   33,   35,  261,   68,   36,   69,   41,
      275,   37,   48,   48,   48,   48,   48,   49,   49,   49,
       49,   49,   26,   83,   27,   28,   50,   50,   50,   50,
       50,   30,   51,   51,   51,   51,   51,  273,   52,   70,

       79,   53,   84,   54,   80,   71,  107,   55,   72,   73,
       56,   57,   58,  134,  271,   59,   26,  269,   27,   28,
       60,   60,   60,   60,   60,   30,   26,  267,   27,   28,
       61,   61,   61,   61,   61,   30,   48,   48,   48,   48,
       48,   26,  265,   27,   28,   77,   77,   77,   77,   77,
       30,   26,  263,   27,   28,   89,   89,   89,   89,   89,
       30,   26,  261,   27,   28,   90,   90,   90,   90,   90,
       30,  104,  104,  104,  104,  104,   26,  105,   27,   28,
      106,  106,  106,  106,  106,   30,  114,  116,  115,  259,
      257,  255,  253,  117,  121,  121,  121,  121,  121,  122,

      122,  122,  122,  122,  104,  104,  104,  104,  104,  132,
      132,  132,  132,  132,  133,  133,  133,  133,  133,   26,
      275,   27,   28,  147,  147,  147,  147,  147,   30,  122,
      122,  122,  122,  122,  155,  155,  155,  155,  155,  133,
      133,  133,  133,  133,  158,  158,  158,  158,  158,  159,
      159,  159,  159,  159,  160,  160,  160,  160,  160,  161,
      161,  161,  161,  161,  162,  162,  162,  162,  162,  163,
      163,  163,  163,  163,  164,  164,  164,  164,  164,  165,
      165,  165,  165,  165,  166,  166,  166,  166,  166,  167,
      167,  167,  167,  167,  168,  168,  168,  168,  168,  169,

      169,  169,  169,  169,   26,  273,   27,   28,  170,  170,
      170,  170,  170,   30,  179,  179,  179,  179,  179,  156,
      197,  197,  197,  197,  197,  271,  180,  179,  179,  179,
      179,  179,  200,  200,  200,  200,  200,  201,  201,  201,
      201,  201,  202,  202,  202,  202,  202,  203,  203,  203,
      203,  203,  204,  204,  204,  204,  204,  205,  205,  205,
      205,  205,  206,  206,  206,  206,  206,  207,  207,  207,
      207,  207,  208,  208,  208,  208,  208,  209,  209,  209,
      209,  209,  210,  210,  210,  210,  210,  211,  211,  211,
      211,  211,  213,  213,  213,  213,  213,  214,  214,  214,

      214,  214,  198,  214,  214,  214,  214,  214,  269,  215,
      228,  228,  228,  228,  228,  229,  229,  229,  229,  229,
      230,  230,  230,  230,  230,  231,  231,  231,  231,  231,
      232,  232,  232,  232,  232,  233,  233,  233,  233,  233,
      234,  234,  234,  234,  234,  235,  235,  235,  235,  235,
      236,  236,  236,  236,  236,  237,  237,  237,  237,  237,
      238,  238,  238,  238,  238,  239,  239,  239,  239,  239,
      240,  240,  240,  240,  240,  228,  228,  228,  228,  228,
      277,  277,  277,  277,  277,  278,  278,  278,  278,  278,
      279,  279,  279,  279,  279,  280,  280,  280,  280,  280,

      281,  281,  281,  281,  281,  283,  283,  283,  283,  283,
      284,  284,  284,  284,  284,  285,  285,  285,  285,  285,
      286,  286,  286,  286,  286,  287,  287,  287,  287,  287,
      288,  288,  288,  288,  288,  289,  289,  289,  289,  289,
      277,  277,  277,  277,  277,  278,  278,  278,  278,  278,
      279,  279,  279,  279,  279,  280,  280,  280,  280,  280,
      281,  281,  281,  281,  281,  283,  283,  283,  283,  283,
      284,  284,  284,  284,  284,  285,  285,  285,  285,  285,
      286,  286,  286,  286,  286,  287,  287,  287,  287,  287,
      288,  288,  288,  288,  288,  289,  289,  289,  289,  289,

       34,  267,   34,   34,  265,   34,   24,  263,  261,  259,
       24,   25,  257,   25,   33,   33,   49,   49,   51,   51,
       92,  255,   92,  108,  253,  108,  157,  252,  157,  178,
      251,  250,  178,  158,  158,  159,  159,  160,  160,  161,
      161,  162,  162,  163,  163,  164,  164,  165,  165,  166,
      166,  167,  167,  168,  168,  169,  169,  199,  249,  199,
      200,  200,  201,  201,  202,  202,  203,  203,  204,  204,
      205,  205,  206,  206,  207,  207,  208,  208,  209,  209,
      210,  210,  211,  211,  229,  229,  230,  230,  231,  231,
      232,  232,  233,  233,  234,  234,  235,  235,  236,  236,

      237,  237,  238,  238,  239,  239,  240,  240,  254,  248,
      254,  256,  247,  256,  258,  246,  258,  260,  245,  260,
      262,  244,  262,  264,  243,  264,  266,  242,  266,  268,
      241,  268,  270,  227,  270,  272,  226,  272,  274,  225,
      274,  276,  224,  276,  282,  223,  282,  222,  221,  220,
      219,  218,  217,  216,  212,  198,  196,  195,  194,  193,
      290,  192,  191,  190,  189,  188,  187,  186,  185,  184,
      183,  182,  181,  177,  176,  175,  174,  173,  172,  171,
      156,  154,  153,  152,  151,  150,  149,  148,  146,  145,
      144,  143,  142,  141,  140,  139,  138,  137,  136,  135,

      290,  131,  130,  129,  128,  127,  126,  125,  124,  123,
       91,  120,  119,  118,  113,  112,  111,  110,  109,  107,
      103,  102,  101,  100,   99,   98,   97,   96,   95,   94,
       93,   91,   88,   87,   86,   85,   82,   81,   78,   76,
       75,   74,   67,   66,   65,   64,   63,   62,   27,   47,
       46,   45,   44,   43,   42,   39,   38,   32,   31,  290,
        3,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290

    } ;

static yyconst short int yy_chk[901] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    8,
        8,    8,    8,    8,    9,    9,    9,    9,    9,   10,
       18,   10,   10,   10,   10,   10,   10,   10,   10,   13,
       13,   13,   13,   13,   14,  282,   41,   14,   41,   18,
      276,   14,   27,   27,   27,   27,   27,   28,   28,   28,
       28,   28,   29,   55,   29,   29,   29,   29,   29,   29,
       29,   29,   30,   30,   30,   30,   30,  274,   30,   42,

       52,   30,   55,   30,   52,   42,  108,   30,   43,   43,
       30,   30,   30,  108,  272,   30,   31,  270,   31,   31,
       31,   31,   31,   31,   31,   31,   32,  268,   32,   32,
       32,   32,   32,   32,   32,   32,   48,   48,   48,   48,
       48,   50,  266,   50,   50,   50,   50,   50,   50,   50,
       50,   60,  264,   60,   60,   60,   60,   60,   60,   60,
       60,   61,  262,   61,   61,   61,   61,   61,   61,   61,
       61,   76,   76,   76,   76,   76,   77,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   84,   85,   84,  260,
      258,  256,  254,   85,   89,   89,   89,   89,   89,   91,

       91,   91,   91,   91,  104,  104,  104,  104,  104,  105,
      105,  105,  105,  105,  107,  107,  107,  107,  107,  121,
      252,  121,  121,  121,  121,  121,  121,  121,  121,  122,
      122,  122,  122,  122,  132,  132,  132,  132,  132,  133,
      133,  133,  133,  133,  135,  135,  135,  135,  135,  136,
      136,  136,  136,  136,  137,  137,  137,  137,  137,  138,
      138,  138,  138,  138,  139,  139,  139,  139,  139,  140,
      140,  140,  140,  140,  141,  141,  141,  141,  141,  142,
      142,  142,  142,  142,  143,  143,  143,  143,  143,  144,
      144,  144,  144,  144,  145,  145,  145,  145,  145,  146,

      146,  146,  146,  146,  147,  251,  147,  147,  147,  147,
      147,  147,  147,  147,  156,  156,  156,  156,  156,  157,
      177,  177,  177,  177,  177,  250,  157,  179,  179,  179,
      179,  179,  181,  181,  181,  181,  181,  182,  182,  182,
      182,  182,  183,  183,  183,  183,  183,  184,  184,  184,
      184,  184,  185,  185,  185,  185,  185,  186,  186,  186,
      186,  186,  187,  187,  187,  187,  187,  188,  188,  188,
      188,  188,  189,  189,  189,  189,  189,  190,  190,  190,
      190,  190,  191,  191,  191,  191,  191,  192,  192,  192,
      192,  192,  197,  197,  197,  197,  197,  198,  198,  198,

      198,  198,  199,  214,  214,  214,  214,  214,  249,  199,
      215,  215,  215,  215,  215,  216,  216,  216,  216,  216,
      217,  217,  217,  217,  217,  218,  218,  218,  218,  218,
      219,  219,  219,  219,  219,  220,  220,  220,  220,  220,
      221,  221,  221,  221,  221,  222,  222,  222,  222,  222,
      223,  223,  223,  223,  223,  224,  224,  224,  224,  224,
      225,  225,  225,  225,  225,  226,  226,  226,  226,  226,
      227,  227,  227,  227,  227,  228,  228,  228,  228,  228,
      253,  253,  253,  253,  253,  255,  255,  255,  255,  255,
      257,  257,  257,  257,  257,  259,  259,  259,  259,  259,

      261,  261,  261,  261,  261,  263,  263,  263,  263,  263,
      265,  265,  265,  265,  265,  267,  267,  267,  267,  267,
      269,  269,  269,  269,  269,  271,  271,  271,  271,  271,
      273,  273,  273,  273,  273,  275,  275,  275,  275,  275,
      277,  277,  277,  277,  277,  278,  278,  278,  278,  278,
      279,  279,  279,  279,  279,  280,  280,  280,  280,  280,
      281,  281,  281,  281,  281,  283,  283,  283,  283,  283,
      284,  284,  284,  284,  284,  285,  285,  285,  285,  285,
      286,  286,  286,  286,  286,  287,  287,  287,  287,  287,
      288,  288,  288,  288,  288,  289,  289,  289,  289,  289,

      291,  248,  291,  291,  247,  291,  292,  246,  245,  244,
      292,  293,  243,  293,  294,  294,  295,  295,  296,  296,
      297,  242,  297,  298,  241,  298,  299,  240,  299,  300,
      239,  238,  300,  301,  301,  302,  302,  303,  303,  304,
      304,  305,  305,  306,  306,  307,  307,  308,  308,  309,
      309,  310,  310,  311,  311,  312,  312,  313,  237,  313,
      314,  314,  315,  315,  316,  316,  317,  317,  318,  318,
      319,  319,  320,  320,  321,  321,  322,  322,  323,  323,
      324,  324,  325,  325,  326,  326,  327,  327,  328,  328,
      329,  329,  330,  330,  331,  331,  332,  332,  333,  333,

      334,  334,  335,  335,  336,  336,  337,  337,  338,  236,
      338,  339,  235,  339,  340,  234,  340,  341,  233,  341,
      342,  232,  342,  343,  231,  343,  344,  230,  344,  345,
      229,  345,  346,  211,  346,  347,  210,  347,  348,  209,
      348,  349,  208,  349,  350,  207,  350,  206,  205,  204,
      203,  202,  201,  200,  196,  180,  176,  174,  172,  171,
      170,  169,  168,  167,  166,  165,  164,  163,  162,  161,
      160,  159,  158,  155,  154,  153,  152,  151,  150,  149,
      134,  131,  130,  129,  127,  126,  125,  124,  120,  119,
      118,  117,  116,  115,  114,  113,  112,  111,  110,  109,

      106,  103,  102,  101,  100,   97,   96,   95,   94,   93,
       92,   88,   87,   86,   83,   82,   81,   80,   79,   78,
       75,   74,   72,   70,   69,   68,   67,   66,   65,   64,
       63,   62,   59,   58,   57,   56,   54,   53,   51,   49,
       46,   44,   40,   39,   38,   37,   36,   33,   25,   24,
       23,   22,   21,   20,   19,   17,   16,   12,   11,    3,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *EP_text;
#define INITIAL 0

#include <stdio.h>
#include <ctype.h>
#include <errno.h>
#include <unistd.h>
#include <stdlib.h>
#include <math.h>
#include <time.h>

#include "pwmig/dsap/coords.h"
#include "pwmig/dsap/stock.h"

static char *Cp ;
/* Lex input, unput
#undef input
#undef unput
#define input() *Cp++
#define unput(c) Cp--
*/

/* Flex input, unput */

#ifdef __STDC__
#define PL_(x) x
#else
#define PL_(x) ( )
#endif /* __STDC__ */
static int my_yyinput PL_(( char *buf, int max_size )) ;
#undef PL_

#undef YY_INPUT
#define YY_INPUT(b,r,ms) (r=my_yyinput(b,ms))


static int Retcode ;
static char *ETimezone = "TZ=                                                                 " ;
#define Timezone (ETimezone+3)
static char *OldTZ = "TZ=                                                                 " ;
static int Year ;
static int Month ;
static int Day ;
static int Hour ;
static int Minute ;
static int Doy ;
static int Num ;
static double Second ;
static double Etime ;
static int Am ;

int mday2doy();
double h2e();

#ifdef EP_wrap
#undef EP_wrap
#endif


/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int EP_wrap YY_PROTO(( void ));
#else
extern int EP_wrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( EP_text, EP_leng, 1, EP_out )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( EP_in )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( EP_in ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, EP_in )) == 0) \
		  && ferror( EP_in ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int EP_lex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after EP_text and EP_leng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;



	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! EP_in )
			EP_in = stdin;

		if ( ! EP_out )
			EP_out = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				EP_create_buffer( EP_in, YY_BUF_SIZE );

		EP_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of EP_text. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 291 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 861 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
{ sscanf(EP_text, "%lf", &Etime);
			if ( Etime < 60.0 )
			    {
			    Second = Etime ;
			    Etime = 0.0 ;
			    }
			}
	YY_BREAK
case 2:
YY_RULE_SETUP
{
			sscanf(EP_text, "%d/%d/%d", &Month, &Day, &Year);
			if (Month > 12 || Day > 31 )
			    complain(0, "Bad date format:'%s'", EP_text);
			}
	YY_BREAK
case 3:
YY_RULE_SETUP
{
			sscanf(EP_text, "%d-%d-%d", &Year, &Month, &Day);
			if (Month > 12 || Day > 31 )
			    complain(0, "Bad date format:'%s'", EP_text);
			}
	YY_BREAK
case 4:
YY_RULE_SETUP
{
			sscanf(EP_text, "%d-%d", &Year, &Doy);
			if (Doy > 366 )
			    complain(0, "Bad date format:'%s'", EP_text);
			}
	YY_BREAK
case 5:
YY_RULE_SETUP
Month = 1;
	YY_BREAK
case 6:
YY_RULE_SETUP
Month = 2;
	YY_BREAK
case 7:
YY_RULE_SETUP
Month = 3;
	YY_BREAK
case 8:
YY_RULE_SETUP
Month = 4;
	YY_BREAK
case 9:
YY_RULE_SETUP
Month = 5;
	YY_BREAK
case 10:
YY_RULE_SETUP
Month = 6;
	YY_BREAK
case 11:
YY_RULE_SETUP
Month = 7;
	YY_BREAK
case 12:
YY_RULE_SETUP
Month = 8;
	YY_BREAK
case 13:
YY_RULE_SETUP
Month = 9;
	YY_BREAK
case 14:
YY_RULE_SETUP
Month = 10;
	YY_BREAK
case 15:
YY_RULE_SETUP
Month = 11;
	YY_BREAK
case 16:
YY_RULE_SETUP
Month = 12;
	YY_BREAK
case 17:
YY_RULE_SETUP
Etime=now() ;
	YY_BREAK
case 18:
YY_RULE_SETUP
sscanf(EP_text, "%d,", &Day);
	YY_BREAK
case 19:
YY_RULE_SETUP
sscanf(EP_text, "%4d%3d", &Year, &Doy);
	YY_BREAK
case 20:
YY_RULE_SETUP
sscanf(EP_text, "%d", &Year);
	YY_BREAK
case 21:
YY_RULE_SETUP
sscanf(EP_text, "(%d)", &Doy ) ;
	YY_BREAK
case 22:
YY_RULE_SETUP
sscanf(EP_text, "%lf", &Etime);
	YY_BREAK
case 23:
YY_RULE_SETUP
{
			int num ;
			sscanf(EP_text, "%d", &num);
			if (num > 31 && num < 2100)
				Year = num;
			else if (Day == -1 && num < 32)
				Day = num;
			else
			    Etime = (double) num ;
			}
	YY_BREAK
case 24:
YY_RULE_SETUP
sscanf(EP_text, ":%d:%lf", &Minute, &Second);
	YY_BREAK
case 25:
YY_RULE_SETUP
sscanf(EP_text, "%d:%d:%lf", &Hour, &Minute, &Second);
	YY_BREAK
case 26:
YY_RULE_SETUP
{
		int jday ;
		sscanf(EP_text, "%d:%d:%d:%lf", &jday, &Hour, &Minute, &Second);
		Year = jday/1000 ;
		Doy = jday % 1000 ;
		}
	YY_BREAK
case 27:
YY_RULE_SETUP
{
		sscanf(EP_text, "%d:%d:%d:%d:%lf", &Year, &Doy, &Hour, &Minute, &Second);
		}
	YY_BREAK
case 28:
YY_RULE_SETUP
{
		int second, msec ;
		sscanf(EP_text, "%d:%d:%d:%d:%d:%d", &Year, &Doy, &Hour, &Minute, &second, &msec);
		Second = second + msec/1000.0 ;
		}
	YY_BREAK
case 29:
YY_RULE_SETUP
{
		char amonth[4] ;
		sscanf(EP_text, "%d:%3s:%d:%d:%d:%lf", &Year, amonth, &Day, &Hour, &Minute, &Second );
		Month = 1 ;
		}
	YY_BREAK
case 30:
YY_RULE_SETUP
{
		char amonth[4] ;
		sscanf(EP_text, "%d:%3s:%d:%d:%d:%lf", &Year, amonth, &Day, &Hour, &Minute, &Second );
		Month = 2 ;
		}
	YY_BREAK
case 31:
YY_RULE_SETUP
{
		char amonth[4] ;
		sscanf(EP_text, "%d:%3s:%d:%d:%d:%lf", &Year, amonth, &Day, &Hour, &Minute, &Second );
		Month = 3 ;
		}
	YY_BREAK
case 32:
YY_RULE_SETUP
{
		char amonth[4] ;
		sscanf(EP_text, "%d:%3s:%d:%d:%d:%lf", &Year, amonth, &Day, &Hour, &Minute, &Second );
		Month = 4 ;
		}
	YY_BREAK
case 33:
YY_RULE_SETUP
{
		char amonth[4] ;
		sscanf(EP_text, "%d:%3s:%d:%d:%d:%lf", &Year, amonth, &Day, &Hour, &Minute, &Second );
		Month = 5 ;
		}
	YY_BREAK
case 34:
YY_RULE_SETUP
{
		char amonth[4] ;
		sscanf(EP_text, "%d:%3s:%d:%d:%d:%lf", &Year, amonth, &Day, &Hour, &Minute, &Second );
		Month = 6 ;
		}
	YY_BREAK
case 35:
YY_RULE_SETUP
{
		char amonth[4] ;
		sscanf(EP_text, "%d:%3s:%d:%d:%d:%lf", &Year, amonth, &Day, &Hour, &Minute, &Second );
		Month = 7 ;
		}
	YY_BREAK
case 36:
YY_RULE_SETUP
{
		char amonth[4] ;
		sscanf(EP_text, "%d:%3s:%d:%d:%d:%lf", &Year, amonth, &Day, &Hour, &Minute, &Second );
		Month = 8 ;
		}
	YY_BREAK
case 37:
YY_RULE_SETUP
{
		char amonth[4] ;
		sscanf(EP_text, "%d:%3s:%d:%d:%d:%lf", &Year, amonth, &Day, &Hour, &Minute, &Second );
		Month = 9 ;
		}
	YY_BREAK
case 38:
YY_RULE_SETUP
{
		char amonth[4] ;
		sscanf(EP_text, "%d:%3s:%d:%d:%d:%lf", &Year, amonth, &Day, &Hour, &Minute, &Second );
		Month = 10 ;
		}
	YY_BREAK
case 39:
YY_RULE_SETUP
{
		char amonth[4] ;
		sscanf(EP_text, "%d:%3s:%d:%d:%d:%lf", &Year, amonth, &Day, &Hour, &Minute, &Second );
		Month = 11 ;
		}
	YY_BREAK
case 40:
YY_RULE_SETUP
{
		char amonth[4] ;
		sscanf(EP_text, "%d:%3s:%d:%d:%d:%lf", &Year, amonth, &Day, &Hour, &Minute, &Second );
		Month = 12 ;
		}
	YY_BREAK
case 41:
YY_RULE_SETUP
sscanf(EP_text, ":%d", &Minute);
	YY_BREAK
case 42:
YY_RULE_SETUP
sscanf(EP_text, "%d:%d", &Hour, &Minute);
	YY_BREAK
case 43:
YY_RULE_SETUP
Am = 1 ;
	YY_BREAK
case 44:
YY_RULE_SETUP
Am = 0 ;
	YY_BREAK
case 45:
YY_RULE_SETUP
;
	YY_BREAK
case 46:
YY_RULE_SETUP
;
	YY_BREAK
case 47:
YY_RULE_SETUP
;
	YY_BREAK
case 48:
YY_RULE_SETUP
{
		    strcpy(Timezone, EP_text ) ;
		    if (check_tz () ) {
			Retcode ++ ;
			register_error ( 0, "str2epoch: can't interpret '%s'\n", EP_text ) ;
			*(Timezone) = 0 ;
		    }
		}
	YY_BREAK
case 49:
YY_RULE_SETUP
{ if ( isprint(*EP_text) )
		    register_error ( 0, "str2epoch: can't interpret '%s'\n", EP_text ) ;
		else
		    register_error ( 0, "str2epoch: can't interpret character 0x%x\n", *EP_text ) ;
		Retcode++ ;
		}
	YY_BREAK
case 50:
YY_RULE_SETUP
ECHO;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed EP_in at a new source and called
			 * EP_lex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = EP_in;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( EP_wrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * EP_text, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of EP_lex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			EP_restart( EP_in );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 291 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 291 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 290);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up EP_text */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					EP_restart( EP_in );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( EP_wrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve EP_text */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void EP_restart( FILE *input_file )
#else
void EP_restart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = EP_create_buffer( EP_in, YY_BUF_SIZE );

	EP_init_buffer( yy_current_buffer, input_file );
	EP_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void EP_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void EP_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	EP_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (EP_wrap()) processing, but the only time this flag
	 * is looked at is after EP_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void EP_load_buffer_state( void )
#else
void EP_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	EP_in = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE EP_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE EP_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in EP_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in EP_create_buffer()" );

	b->yy_is_our_buffer = 1;

	EP_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void EP_delete_buffer( YY_BUFFER_STATE b )
#else
void EP_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void EP_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void EP_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	EP_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void EP_flush_buffer( YY_BUFFER_STATE b )
#else
void EP_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		EP_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE EP_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE EP_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in EP_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	EP_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE EP_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE EP_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return EP_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE EP_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE EP_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in EP_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = EP_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in EP_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up EP_text. */ \
		EP_text[EP_leng] = yy_hold_char; \
		yy_c_buf_p = EP_text + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		EP_leng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	EP_lex();
	return 0;
	}
#endif


int EP_wrap() { return 1 ; }

static int
check_tz ()
{
    int retcode = 0 ;
    char *tz ;
    tz = getenv("TZ") ;
    strcpy(OldTZ+3, tz) ;
    putenv ( ETimezone ) ;
    tz = getenv("TZ") ;
    errno = 0 ;
    tzset() ;
    /* show_tz("str2epoch: check_tz" ) ; */
    if ( errno != 0 ) {
	errno = 0 ;
        retcode = -1 ;
    }
    return retcode ;
}

int zstr2epoch ( char *s, double *e )
{
    Cp = s ;
    Retcode = 0 ;

    *Timezone = 0 ;
    Year = 1970 ;
    Month = -1;
    Day = -1;
    Hour = 0;
    Minute = 0;
    Doy = 0;
    Num = 0;
    Second = 0;
    Etime = 0.0;
    Am = - 1 ;

    EP_lex () ;
    EP_restart(stdin) ;

    if ( Month < 1 ) Month = 1 ;
    if ( Day < 1 ) Day = 1 ;
    if ( Am == 1 && Hour == 12) Hour -= 12; /* allow 12:30 am to mean 0:30 am */
    if ( Am == 0 && Hour <  12) Hour += 12;

    if ( Etime == 0.0 ) {
	if (Doy == 0) {
	    Doy = mday2doy(Year, Month, Day) ;
	}
	if ( Year < 100 ) Year += 1900 ;
	Etime = h2e ( Year, Doy, Hour, Minute, Second ) ;
    }

    if (*Timezone != 0 ) {
	    struct tm utm ;
	    time_t utime ;
	    int year, doy, hour, minute, month, mday ;
	    double second, msec ;
	    /* don't have to run tzset, because it was already done in check_tz above */
	    e2h ( Etime, &year, &doy, &hour, &minute, &second ) ;
	    msec = Etime - floor(Etime) ;
	    doy2mday ( doy, year, &month, &mday ) ;
	    utm.tm_sec = second ;
	    utm.tm_min = minute ;
	    utm.tm_hour = hour ;
	    utm.tm_mon = month-1 ;
	    utm.tm_mday = mday ;
	    utm.tm_year = year - 1900 ;
	    utm.tm_isdst = -1 ;
	    utime = mktime ( &utm ) ;
	    if ( utime == -1 ) {
		register_error ( 0, "Can't convert to local timezone before 1970\n" ) ;
		Retcode++ ;
	    }
	    Etime = ((double) utime) + msec ;
	    /* now restore the original timezone */
	    putenv ( OldTZ ) ;
	    tzset() ;
	    /* show_tz ( "str2epoch: restoring" ) ; */
    }

    *e = Etime ;

    return Retcode ;
}


double str2epoch ( s )
char *s ;
{
    double e ;

    zstr2epoch ( s, &e ) ;

    return e ;
}

static int my_yyinput ( buf, ms )
char *buf ;
int ms ;
{
    int n ;

    n = MIN ( ms, strlen(Cp)) ;
    memcpy ( buf, Cp, n ) ;
    Cp += n ;
    return n ;
}

/* $Id: str2epoch.l,v 1.2 1997/04/29 12:57:39 danq Exp $ */
