FROM ghcr.io/mspass-team/mspass:dev

LABEL maintainer="Ian Wang <yinzhi.wang.cug@gmail.com>"

# Add cxx library
ADD cxx /parallel_pwmig/cxx
ADD data /parallel_pwmig/data
ADD setup.py /parallel_pwmig/setup.py
ADD python /parallel_pwmig/python
RUN MSPASS_HOME=/usr/local pip3 install --global-option build --global-option --debug /parallel_pwmig -v
RUN pip3 install vtk

